### PR TITLE
17 -- HTMLrats

### PR DESCRIPTION
**Pull request by al-the-x**

### CODE REVIEW

**Comment by al-the-x** [comment]
#### Blockers
- BEAST MODE AGAIN?
- Why counter? Model what?
- Trying too many things...
- how move pieces, CSS?!?
- OOP hard.
- going backwards
- how test?
- catching up slows you down

**Comment by jorgehjr84** [comment]
### 3 Little Things
- For Loops
- Chess pieces being responsive ( being able to resize them )
- Icon size

### Parking Lot
- Tests ( when and how to implement test in your programming )
- Model vs Controller
- Values from HTML Forms
- 'Plan of attack' for chess game
- Package management ( When to install, why, and when to install globally ? )
- Revealing Module Pattern

**Comment by gatorpazz** [comment]
Why we skip 16????

**Comment by al-the-x** [comment]
@gatorpazz I WILL HAVE ORDER! I WILL HAVE PERFECTION!

**Pull request merged**
