### PR TITLE
25 -- Conquest of the Planet of the APIs

### PR DESCRIPTION
**Pull request by al-the-x**
## Rituals (~1h 15m)
- **Standup Meeting** (~15m)
- **Three Little Things** (~30m)
- **Homework Review** (~30m)

### CODE REVIEW

**Comment by al-the-x** [comment]
### Blockers
- That `<template>` tag, tho...
- Using the grid?
- Being off assignment...

**Comment by al-the-x** [comment]
Link: http://www.joelonsoftware.com/articles/fog0000000069.html

**Comment by MStaehling** [comment]
- template tag
- Utilizing Media Queries
- Grids inside of grids
- best way to relocate tabs

**Comment by al-the-x** [comment]
The Prequel: al-the-x/TIY-Github#2

**Comment by al-the-x** [comment]
Today's Adventure: al-the-x/TIY-Github#3

**Pull request merged**
