### PR TITLE
13 -- In the HTML of the Night

### PR DESCRIPTION
**Pull request by al-the-x**
## Rituals (~1h 15m)
- **Standup Meeting** (~15m)
- **Three Little Things** (~30m)
- **Homework Review** (~30m)
### Yak Shaving: Never run `browser-sync` again...
- [x] Create a `package.json` with `npm init`
- [x] Record my dependencies: `npm link browser-sync --save`
- [x] Tell `npm` how to run `browser-sync`...
  - [x] edit `package.json`
  - [x] add `"start"` to `"scripts"` dictionary
  - [x] run `npm run-scripts start` AKA `npm start`
- [x] I guess we need some boilerplate...
  - `npm install -g yo generator-h5bp`
  - `yo h5bp` + some questions
  - `git status` and _woah_
### Let's build that [Vertical Timeline](http://tympanus.net/Blueprints/VerticalTimeline/)!
- [x] Start with a plan...
  - [x] Sktich the breakpoints...
  - [x] Markup the specs...
  - [x] Discuss the data model...
- [x] Time for a [MF'g Website](http://motherfuckingwebsite.com)!
- [ ] Okay, now for CSS... No, CSS sucks!
  - `npm install -g node-sass`
  - `node-sass styles.scss`
  - `npm link --save node-sass`
- [ ] Awesome, now let's never run _that_ again...
  - edit `package.json`
  - `npm run-script sass`
  - so which file do we commit?
### BONUS: What's with that @$$-old version of jQuery?
- use `bower` to install better ones
- and let `wiredep` wire them up for you!
  - `npm install -g wiredep`
  - `npm link --save wiredep`
  - add comment markers to `index.html`
  - `wiredep -s index.html`
- [automate with `.bowerrc`](https://github.com/bower/bower/blob/master/HOOKS.md) or `npm run-scripts` (as above)

### CODE REVIEW

**Comment by al-the-x** [comment]
### Blockers
- Chessboard Setup
- Centering pseudo elements
- Behind on old assignments
- Display active tab
- Planning vs Coding: Time Management
- jQuery vs Vanilla JS?!?!?!

**Comment by pcreglow** [comment]
3 little things...
-active tabs on FullWidthTabs
-student-roster(modify TEMPLATE.md in separate PR)
-center pseudo element

**Comment by kmattiko** [comment]
**_3 Little Things**_
1. Styling Active Tab on FullWidthTabs
2. Separate pull requests on the Student Roster
3. Centering Pseudo Elements

**Comment by al-the-x** [comment]
Maybe just `touch package.json` next time...?

**Comment by al-the-x** [comment]
Vertical Timeline

Breakpoints:
- `max-width: 65.375em`: font-size change for time
- `max-width: 47.2em`: layout change

View:
- big bad container
  - each entry
    - date and time
    - post / article
      - caret on post / article
      - heading inside post / article
      - body content inside post / article
    - icon (and it's a circle, ZOMG!!)

Model:

``` javascript
[
  { "date": "4/10/13", "time": "18:30", 
    "device": "mobile?", 
    "title": "Ricebean black-eyed pea", "text": ". . ." 
  },
  . . .
]
```

**Comment by al-the-x** [comment]
In future, make tool installs a part of Monday homework...

**Comment by MStaehling** [comment]
text is white in article tag

**Comment by JessyRiordan** [comment]
The article background alternates between a light blue and a dark(ish) blue.

**Comment by pope410211** [comment]
Three columns. Left to right.

**Comment by pcreglow** [comment]
font-color of the date is lightgray
font-color of the time matches the background color of the corresponding article column

**Comment by JessyRiordan** [comment]
Icons...

**Pull request merged**
